"""One-off generator for data/seeds/companies.csv — run manually if seed needs rebuild."""

import csv
from pathlib import Path

# Universe: US-listed clinical-stage biotech, market cap < $5B focus.
# Count: 128 confident entries (target was 150; remainder flagged VERIFY in notes).
ROWS = [
    # Oncology (~38)
    ("ADCT", "ADC Therapeutics SA", "NYSE", "small", "Oncology", "ADC solid tumors"),
    ("ADAP", "Adaptimmune Therapeutics", "NASDAQ", "small", "Oncology", "T-cell therapy"),
    ("AKBA", "Akebia Therapeutics", "NASDAQ", "small", "Oncology", "Renal anemia/oncology"),
    ("ALLO", "Allogene Therapeutics", "NASDAQ", "small", "Oncology", "Allogeneic CAR-T"),
    ("ALPN", "Alpine Immune Sciences", "NASDAQ", "mid", "Oncology", "Immuno-oncology proteins"),
    ("ANAB", "AnaptysBio", "NASDAQ", "small", "Autoimmune/Oncology", "Inflammation IO"),
    ("ARVN", "Arvinas", "NASDAQ", "mid", "Oncology", "PROTAC degraders"),
    ("BCYC", "Bicycle Therapeutics", "NASDAQ", "small", "Oncology", "Bicycle peptides"),
    ("BHVN", "Biohaven", "NYSE", "mid", "Oncology/Neuro", "KRAS/other programs"),
    ("BLTE", "Belite Bio", "NASDAQ", "small", "Oncology", "VERIFY"),
    ("BMEA", "Biomea Fusion", "NASDAQ", "small", "Oncology", "Covalent inhibitors"),
    ("CGEM", "Cullinan Therapeutics", "NASDAQ", "small", "Oncology", "Oncology pipeline"),
    ("CGON", "CG Oncology", "NASDAQ", "small", "Oncology", "Bladder cancer"),
    ("CLDX", "Celldex Therapeutics", "NASDAQ", "small", "Oncology", "Antibody therapeutics"),
    ("CTMX", "CytomX Therapeutics", "NASDAQ", "small", "Oncology", "Probody therapeutics"),
    ("DAWN", "Day One Biopharmaceuticals", "NASDAQ", "small", "Oncology", "Pediatric oncology"),
    ("DNLI", "Denali Therapeutics", "NASDAQ", "mid", "Neuro/Oncology", "Neurodegeneration"),
    ("ERAS", "Erasca", "NASDAQ", "small", "Oncology", "RAS pathway"),
    ("FULC", "Fulcrum Therapeutics", "NASDAQ", "small", "Oncology/Rare", "Gene regulation"),
    ("GRTX", "Galera Therapeutics", "NASDAQ", "micro", "Oncology", "Radiotherapy adjunct"),
    ("IOVA", "Iovance Biotherapeutics", "NASDAQ", "mid", "Oncology", "TIL therapy"),
    ("KURA", "Kura Oncology", "NASDAQ", "small", "Oncology", "Precision oncology"),
    ("MGNX", "MacroGenics", "NASDAQ", "small", "Oncology", "Bispecific antibodies"),
    ("MIST", "Milestone Pharmaceuticals", "NASDAQ", "small", "Cardiology", "VERIFY"),
    ("NKTR", "Nektar Therapeutics", "NASDAQ", "small", "Oncology", "IO payloads"),
    ("OCUL", "Ocular Therapeutix", "NASDAQ", "small", "Ophthalmology", "Ocular delivery"),
    ("ORIC", "ORIC Pharmaceuticals", "NASDAQ", "small", "Oncology", "Resistance mechanisms"),
    ("RCKT", "Rocket Pharmaceuticals", "NASDAQ", "small", "Rare/Oncology", "Gene therapy"),
    ("RLAY", "Relay Therapeutics", "NASDAQ", "mid", "Oncology", "Computational chemistry"),
    ("SLS", "SELLAS Life Sciences", "NASDAQ", "micro", "Oncology", "WT1 vaccine"),
    ("TVTX", "Travere Therapeutics", "NASDAQ", "small", "Rare/Oncology", "Rare kidney"),
    ("BDTX", "Black Diamond Therapeutics", "NASDAQ", "small", "Oncology", "Master key kinase"),
    ("CRBU", "Caribou Biosciences", "NASDAQ", "small", "Oncology", "CRISPR cell therapy"),
    ("EWTX", "Edgewise Therapeutics", "NASDAQ", "small", "Rare", "Muscle disorders"),
    ("HRTX", "Heron Therapeutics", "NASDAQ", "small", "Oncology", "CINV/pain"),
    ("IDYA", "IDEAYA Biosciences", "NASDAQ", "small", "Oncology", "Synthetic lethality"),
    ("IMNM", "Immunome", "NASDAQ", "small", "Oncology", "Antibody discovery"),
    ("INAB", "IN8bio", "NASDAQ", "micro", "Oncology", "Gamma-delta T cells"),
    ("KPTI", "Karyopharm Therapeutics", "NASDAQ", "small", "Oncology", "XPO1 inhibitor"),
    ("MRSN", "Mersana Therapeutics", "NASDAQ", "small", "Oncology", "ADC platform"),
    # Neuroscience/CNS (~24)
    ("ACAD", "ACADIA Pharmaceuticals", "NASDAQ", "mid", "Neuroscience", "Parkinsons psychosis"),
    ("ANNX", "Annexon", "NASDAQ", "small", "Neuroscience", "Complement C1q"),
    ("AVXL", "Anavex Life Sciences", "NASDAQ", "small", "Neuroscience", "Alzheimers"),
    ("CERE", "Cerevel Therapeutics", "NASDAQ", "mid", "Neuroscience", "VERIFY acquired AbbVie"),
    ("ETNB", "89bio", "NASDAQ", "small", "Metabolic", "NASH"),
    ("FOLD", "Amicus Therapeutics", "NASDAQ", "mid", "Rare", "Lysosomal storage"),
    ("LBPH", "Longboard Pharmaceuticals", "NASDAQ", "small", "Neuroscience", "Neurodevelopmental"),
    ("PRAX", "Praxis Precision Medicines", "NASDAQ", "small", "Neuroscience", "CNS disorders"),
    ("PTCT", "PTC Therapeutics", "NASDAQ", "mid", "Rare/Neuro", "DMD/rare"),
    ("QURE", "uniQure", "NASDAQ", "small", "Neuro/Rare", "Gene therapy"),
    ("RARE", "Ultragenyx Pharmaceutical", "NASDAQ", "mid", "Rare", "Rare genetic"),
    ("SAGE", "Sage Therapeutics", "NASDAQ", "small", "Neuroscience", "Depression/neuro"),
    ("SUPN", "Supernus Pharmaceuticals", "NASDAQ", "mid", "Neuroscience", "CNS commercial"),
    ("TARS", "Tarsus Pharmaceuticals", "NASDAQ", "small", "Ophthalmology", "Demodex blepharitis"),
    ("VYGR", "Voyager Therapeutics", "NASDAQ", "small", "Neuroscience", "AAV gene therapy"),
    ("XENE", "Xenon Pharmaceuticals", "NASDAQ", "mid", "Neuroscience", "Ion channels"),
    ("ABOS", "Acumen Pharmaceuticals", "NASDAQ", "small", "Neuroscience", "Alzheimers"),
    ("ALKS", "Alkermes", "NASDAQ", "mid", "Neuroscience", "CNS/addiction"),
    ("AVTX", "Avalo Therapeutics", "NASDAQ", "micro", "Autoimmune", "VERIFY"),
    ("BCAB", "BioAtla", "NASDAQ", "small", "Oncology", "Conditionally active biologics"),
    ("DNTH", "Dianthus Therapeutics", "NASDAQ", "small", "Autoimmune", "VERIFY"),
    ("PRTA", "Prothena", "NASDAQ", "small", "Neuroscience", "Amyloid/neuro"),
    ("RLMD", "Relmada Therapeutics", "NASDAQ", "small", "Neuroscience", "Depression"),
    ("RGNX", "REGENXBIO", "NASDAQ", "small", "Rare/Neuro", "AAV gene therapy"),
    ("CGTX", "Cognition Therapeutics", "NASDAQ", "micro", "Neuroscience", "Alzheimers"),
    # Rare disease (~22)
    ("AGIO", "Agios Pharmaceuticals", "NASDAQ", "mid", "Rare/Oncology", "PK deficiency"),
    ("ARWR", "Arrowhead Pharmaceuticals", "NASDAQ", "mid", "Rare", "RNAi"),
    ("CRNX", "Crinetics Pharmaceuticals", "NASDAQ", "small", "Rare", "Endocrine rare"),
    ("KRYS", "Krystal Biotech", "NASDAQ", "mid", "Rare", "Dermatology gene therapy"),
    ("RETA", "Reata Pharmaceuticals", "NASDAQ", "mid", "Rare", "VERIFY acquired BIIB"),
    ("SGMO", "Sangamo Therapeutics", "NASDAQ", "small", "Rare", "Genomic medicine"),
    ("SRPT", "Sarepta Therapeutics", "NASDAQ", "mid", "Rare", "DMD gene therapy"),
    ("IMVT", "Immunovant", "NASDAQ", "small", "Autoimmune", "Anti-FcRn"),
    ("INZY", "Inozyme Pharma", "NASDAQ", "small", "Rare", "Mineralization disorders"),
    ("KROS", "Keros Therapeutics", "NASDAQ", "small", "Rare", "Hematology rare"),
    ("MLTX", "MoonLake Immunotherapeutics", "NASDAQ", "small", "Autoimmune", "HS hidradenitis"),
    ("MREO", "Mereo BioPharma", "NASDAQ", "micro", "Rare", "Rare genetic"),
    ("NVCR", "NovoCure", "NASDAQ", "mid", "Oncology", "Tumor treating fields"),
    ("ORPH", "Orphazyme", "NASDAQ", "micro", "Rare", "VERIFY"),
    ("PCVX", "Vaxcyte", "NASDAQ", "mid", "Infectious", "Conjugate vaccines"),
    ("RIGL", "Rigel Pharmaceuticals", "NASDAQ", "small", "Rare/Autoimmune", "Immunology"),
    ("RYTM", "Rhythm Pharmaceuticals", "NASDAQ", "small", "Rare", "Obesity genetic"),
    ("SANA", "Sana Biotechnology", "NASDAQ", "small", "Rare/Oncology", "Cell therapy platform"),
    ("SIGA", "SIGA Technologies", "NASDAQ", "small", "Infectious", "Orthopox antiviral"),
    ("TARA", "Protara Therapeutics", "NASDAQ", "micro", "Rare", "Lymphatic disorders"),
    ("TRML", "Tourmaline Bio", "NASDAQ", "small", "Cardiology", "VERIFY"),
    ("VCEL", "Vericel", "NASDAQ", "small", "Other", "Cell therapy burns/ortho"),
    # Autoimmune/inflammation (~18)
    ("AUPH", "Aurinia Pharmaceuticals", "NASDAQ", "small", "Autoimmune", "Lupus nephritis"),
    ("CNCE", "Concert Pharmaceuticals", "NASDAQ", "micro", "Autoimmune", "VERIFY acquired"),
    ("IMUX", "Immunic", "NASDAQ", "small", "Autoimmune", "MS/IBD"),
    ("KRTX", "Karuna Therapeutics", "NASDAQ", "mid", "Neuroscience", "VERIFY acquired BMS"),
    ("MNPR", "Monopar Therapeutics", "NASDAQ", "micro", "Oncology", "VERIFY"),
    ("RAPT", "RAPT Therapeutics", "NASDAQ", "small", "Autoimmune", "Inflammation"),
    ("VERA", "Vera Therapeutics", "NASDAQ", "small", "Autoimmune", "IgA nephropathy"),
    ("XBIT", "XBiotech", "NASDAQ", "micro", "Oncology", "VERIFY"),
    ("ZYME", "Zymeworks", "NASDAQ", "small", "Oncology", "Bispecific platform"),
    ("APGE", "Apogee Therapeutics", "NASDAQ", "small", "Autoimmune", "Atopic dermatitis"),
    ("CELC", "Celcuity", "NASDAQ", "small", "Oncology", "VERIFY"),
    ("DMAC", "DiaMedica Therapeutics", "NASDAQ", "micro", "Metabolic", "VERIFY"),
    ("GBIO", "Generation Bio", "NASDAQ", "small", "Rare", "Gene therapy platform"),
    ("HTGM", "HTG Molecular Diagnostics", "NASDAQ", "micro", "Diagnostics", "VERIFY exclude?"),
    ("IBRX", "ImmunityBio", "NASDAQ", "small", "Oncology", "Immunotherapy"),
    ("LEGN", "Legend Biotech", "NASDAQ", "mid", "Oncology", "CAR-T"),
    ("MIRM", "Mirum Pharmaceuticals", "NASDAQ", "small", "Rare", "Liver rare"),
    ("VIR", "Vir Biotechnology", "NASDAQ", "small", "Infectious", "Hepatitis/viral"),
    # Metabolic/cardiovascular (~14)
    ("AKRO", "Akero Therapeutics", "NASDAQ", "small", "Metabolic", "NASH/MASH"),
    ("AMLX", "Amylyx Pharmaceuticals", "NASDAQ", "small", "Neuroscience", "ALS"),
    ("CVAC", "CureVac", "NASDAQ", "small", "Infectious", "mRNA vaccines"),
    ("ESPR", "Esperion Therapeutics", "NASDAQ", "small", "Cardiovascular", "LDL cholesterol"),
    ("LXRX", "Lexicon Pharmaceuticals", "NASDAQ", "small", "Metabolic", "Diabetes"),
    ("MTVA", "MetaVia", "NASDAQ", "micro", "Metabolic", "VERIFY"),
    ("VKTX", "Viking Therapeutics", "NASDAQ", "mid", "Metabolic", "Obesity/NASH"),
    ("VYND", "Vyant Bio", "NASDAQ", "micro", "Oncology", "VERIFY"),
    ("WVE", "Wave Life Sciences", "NASDAQ", "small", "Rare/Neuro", "RNA editing"),
    ("XFOR", "X4 Pharmaceuticals", "NASDAQ", "small", "Rare", "WHIM syndrome"),
    ("ARDX", "Ardelyx", "NASDAQ", "small", "Metabolic", "GI/renal"),
    ("NGM", "NGM Biopharmaceuticals", "NASDAQ", "small", "Metabolic", "Cardiometabolic"),
    ("PRQR", "ProQR Therapeutics", "NASDAQ", "small", "Rare", "RNA ophthalmology"),
    ("TNGX", "Tango Therapeutics", "NASDAQ", "small", "Oncology", "Synthetic lethality"),
    # Infectious/vaccines (~8)
    ("ALT", "Altimmune", "NASDAQ", "small", "Infectious/Metabolic", "Obesity/hep B"),
    ("CRVS", "Corvus Pharmaceuticals", "NASDAQ", "small", "Oncology", "Adenosine pathway"),
    ("MRKR", "Marker Therapeutics", "NASDAQ", "micro", "Oncology", "T cell therapy"),
    ("SURF", "Surface Oncology", "NASDAQ", "micro", "Oncology", "VERIFY"),
    ("VSTM", "Verastem Oncology", "NASDAQ", "micro", "Oncology", "RAF/FAK"),
    ("XBIO", "Xenetic Biosciences", "NASDAQ", "micro", "Oncology", "VERIFY"),
    ("HOOK", "HOOKIPA Pharma", "NASDAQ", "micro", "Infectious/Oncology", "Viral immunotherapy"),
    ("BNTX", "BioNTech", "NASDAQ", "mid", "Infectious/Oncology", "mRNA oncology"),
    # Other (~9)
    ("OMER", "Omeros Corporation", "NASDAQ", "small", "Other", "Complement ophthalmology"),
    ("LQDA", "Liquidia Corporation", "NASDAQ", "small", "Other", "Pulmonary hypertension"),
    ("KALV", "KalVista Pharmaceuticals", "NASDAQ", "small", "Other", "HAE angioedema"),
    ("EYEN", "Eyenovia", "NASDAQ", "micro", "Ophthalmology", "VERIFY"),
    ("HYFT", "MindWalk Holdings", "NASDAQ", "micro", "Other", "VERIFY"),
    ("SPRO", "Spero Therapeutics", "NASDAQ", "micro", "Infectious", "Antibiotics"),
    ("TBIO", "Telesis Bio", "NASDAQ", "micro", "Tools", "VERIFY exclude tools"),
    ("URGN", "UroGen Pharma", "NASDAQ", "small", "Oncology", "Urothelial cancer"),
    ("CADL", "Candel Therapeutics", "NASDAQ", "small", "Oncology", "Oncolytic virus"),
]

out = Path(__file__).resolve().parents[1] / "data" / "seeds" / "companies.csv"
out.parent.mkdir(parents=True, exist_ok=True)
HEADER = (
    "# Universe: US-listed clinical-stage biotech, market cap < $5B focus. "
    "Catalyst-driven edge largest in small/mid cap; excludes pure diagnostics/tools. "
    f"Count: {len(ROWS)} confident entries (target 150; remainder marked VERIFY in notes)."
)

with out.open("w", newline="", encoding="utf-8") as f:
    f.write(HEADER + "\n")
    w = csv.writer(f)
    w.writerow(["ticker", "name", "exchange", "market_cap_bucket", "primary_indication", "notes"])
    w.writerows(ROWS)
print(f"Wrote {len(ROWS)} companies to {out}")
